### ISSUE TITLE
Lovelace error: Custom element doesn't exist: wtw-card.

### ISSUE THREAD

**Issue by SgtFoose** [Mosibi/whr_930#27]
``` 
title: WTW
views:
  - badges: []
    cards:
      - entities:
          - entity: sensor.wtw_type
            icon: mdi:arrow-left-right-bold
            name: Type
          - entity: sensor.wtw_size
            icon: mdi:checkbox-blank-circle-outline
            name: Size
          - entity: sensor.wtw_bypass_present
            icon: mdi:checkbox-blank-circle-outline
            name: Bypass present
          - entity: sensor.wtw_enthalpy_present
            icon: mdi:checkbox-blank-circle-outline
            name: Enthalpy present
          - entity: sensor.wtw_ewt_present
            icon: mdi:checkbox-blank-circle-outline
            name: EWT present
          - entity: sensor.wtw_options_present
            icon: mdi:checkbox-blank-circle-outline
            name: Options present
          - entity: sensor.wtw_preheating_present
            icon: mdi:checkbox-blank-circle-outline
            name: Preheating present
          - entities:
              - sensor.wtw_p10_active
              - sensor.wtw_p11_active
              - sensor.wtw_p12_active
              - sensor.wtw_p13_active
              - sensor.wtw_p14_active
              - sensor.wtw_p15_active
              - sensor.wtw_p16_active
              - sensor.wtw_p17_active
              - sensor.wtw_p18_active
              - sensor.wtw_p19_active
              - sensor.wtw_p90_active
              - sensor.wtw_p91_active
              - sensor.wtw_p92_active
              - sensor.wtw_p93_active
              - sensor.wtw_p94_active
              - sensor.wtw_p95_active
              - sensor.wtw_p96_active
              - sensor.wtw_p97_active
            head:
              label: Active states (P#)
              type: section
            type: custom:fold-entity-row
          - type: divider
          - entity: sensor.wtw_filter_status
            icon: mdi:filter
            name: Filter
          - entity: sensor.wtw_preheating_state
            icon: mdi:radiator
            name: Preheating active
          - entity: sensor.wtw_summer_mode
            icon: mdi:weather-sunny
            name: Summer mode
        title: WTW
        type: entities
      - type: custom:wtw-card
      - columns: 3
        entities:
          - entity: sensor.wtw_return_air_level
            icon: mdi:fan
            name: Fan speed (%) return
          - entity: sensor.wtw_supply_air_level
            icon: mdi:fan
            name: Fan speed (%) supply
          - entity: sensor.wtw_exhaust_fan_rpm
            icon: mdi:fan
            name: Fan speed (rpm) exhaust
          - entity: sensor.wtw_intake_fan_rpm
            icon: mdi:fan
            name: Fan speed (rpm) intake
          - entity: sensor.wtw_ventilation_level
            icon: mdi:fan
            name: Current level
        show_icon: true
        show_name: true
        show_state: true
        title: Ventilation
        type: glance
      - columns: 2
        entities:
          - entity: sensor.wtw_outside_temperature
            name: Supply to WTW
          - entity: sensor.wtw_exhaust_temperature
            name: Return from WTW
          - entity: sensor.wtw_supply_temperature
            name: Supply to house
          - entity: sensor.wtw_return_temperature
            name: Return from house
        title: Temperatures
        type: glance
      - entities:
          - entity: sensor.wtw_bypass_valve
            icon: mdi:electric-switch
            name: Valve
          - entity: sensor.wtw_bypass_correction
            icon: mdi:electric-switch
            name: Correction value
          - entity: sensor.wtw_bypass_factor
            icon: mdi:electric-switch
            name: Factor
          - entity: sensor.wtw_bypass_open_hours
            icon: mdi:electric-switch
            name: Open (hours)
          - entity: sensor.wtw_bypass_step
            icon: mdi:electric-switch
            name: Step
          - entity: sensor.wtw_motor_current_bypass
            icon: mdi:electric-switch
            name: Motor current
        title: Bypass
        type: entities
      - entities:
          - entity: fan.wtw_ventilation
          - entity: input_number.set_wtw_comfort_temperature
        title: Settings
        type: entities
      - entities:
          - entity: sensor.wtw_motor_current_preheating
            name: Preheating motor current
          - entity: sensor.wtw_preheating_hours
            name: Preheating (hours)
          - entity: sensor.wtw_preheating_state
            name: Preheating state
          - entity: sensor.wtw_preheating_valve
            name: Preheating valve
          - type: divider
          - entity: sensor.wtw_frost_protection_active
            name: Frost protection active
          - entity: sensor.wtw_frost_protection_hours
            name: Frost protection (hours)
          - entity: sensor.wtw_frost_protection_level
            name: Frost protection level
          - entity: sensor.wtw_frost_protection_minutes
            name: Frost protection (minutes)
        title: Preheating / Frost protection
        type: entities
    icon: mdi:fan
    path: wtw
    title: WTW
   ```

Please advise!
![whr930 test1](https://user-images.githubusercontent.com/17387175/212293054-028a193c-840f-4b03-b6b4-fe3c57600bfe.png)
