### ISSUE TITLE
get_operating_hours could not get serial data

### ISSUE THREAD

**Issue by iamrellah** [Mosibi/whr_930#8]
I receive the following when running the python script:

```
02-07-2020 20:54:17 WARNING: Received garbage data, ignored ...
02-07-2020 20:54:17 WARNING: get_operating_hours function could not get serial data
Traceback (most recent call last):
  File "whr930.py", line 885, in <module>
    sys.exit(main())
  File "whr930.py", line 874, in main
    get_preheating_status()
  File "whr930.py", line 587, in get_preheating_status
    int(data[7], 16)
KeyError: 255
```

Edit:
Commeting out these lines in whr930.py does make it work and I'm able to control the unit.

```
line 873            get_operating_hours()
line 874            get_preheating_status()
```

I do however get these messages a lot:

```
02-07-2020 22:01:53 WARNING: Received garbage data, ignored ...
02-07-2020 22:01:53 WARNING: get_fan_status function could not get serial data
```

**Comment by Mosibi** [comment]
Thanks for reporting!

The error itself is harmless, I do a lot of validation to ensure that a message received is valid and complete and since serial communication can be  flaky sometimes it happens that a message which is received is not compliant to the specification. I see those message's also on my own WHR930 a few times a hour.

I will submit a new version in a few minutes where those warning messages are not shown anymore. If you still want to see them, set the 'warning' parameter to True. For the Traceback I added an exception handler.

**Comment by iamrellah** [comment]
Thank you! All working now. 
Another question, did you ever try to integrate the whr930 into google home using home assistant?

**Comment by Mosibi** [comment]
> Thank you! All working now.
> Another question, did you ever try to integrate the whr930 into google home using home assistant?

Not with google home, but I did an integration with Amazon Alexa. I created a virtual device “ventilation” using the emulated-hue component, where off is level 2 (our default level) and 3 is on. So we can say, Alexa turn ventilation on/off

**Comment by iamrellah** [comment]
Thats sounds awesome! Could you maybe share you script? Might help me to get it working with google home. Would highly appreciate it! 

Edit: Was able to get something working. I'm able to control the WHR using Google Home/Homekit using this in the configuration.yaml. Only thing that doesn't work yet is the state topic, so it will change the speed value but not read what state is. Pretty basic so far. Looking into what needs to be done to get the state working. 

Edit2:
Turns out getting the state is pretty simple.
Just needed to add this:
```
    state_value_template: "{{ states.sensor.wtw_ventilation_level.state }}"
    speed_value_template: "{{ states.sensor.wtw_ventilation_level.state }}"
```

So the full config becomes:
As you can see in my config below if set payload off to 1. If set to 0 the WHR will go into "Away" mode.

```
fan:
  - platform: mqtt
    name: "Ventilatie"
    state_topic: "house/2/attic/wtw/ventilation_level"
    command_topic: "house/2/attic/wtw/set_ventilation_level"
    speed_state_topic: "house/2/attic/wtw/ventilation_level"
    speed_command_topic: "house/2/attic/wtw/set_ventilation_level"
    state_value_template: "{{ states.sensor.wtw_ventilation_level.state }}"
    speed_value_template: "{{ states.sensor.wtw_ventilation_level.state }}"
    payload_off: "1"
    payload_on: "3"
    payload_low_speed: "1"
    payload_medium_speed: "2"
    payload_high_speed: "3"
    speeds:
      - "off"
      - low
      - medium
      - high
```

**Comment by Mosibi** [comment]
Ah, you already have some. I use the switch variant, but I saw that indeed there is also a fan component now. This what I have configured

```
switch:
  - platform: mqtt
    name: "Ventilation"
    command_topic: "house/2/attic/wtw/set_ventilation_level"
    state_topic: "house/2/attic/wtw/ventilation_level"
    qos: 0
    payload_on: "3"
    payload_off: "2"
    state_on: "3"
    state_off: "2"
    optimistic: false

emulated_hue:
  advertise_ip: <ip address>
  expose_by_default: false
  exposed_domains:
    - switch
  entities:
    switch.ventilation:
      hidden: false
```
